### ISSUE TITLE
Pagination does not update when using search function

### ISSUE THREAD

**Issue by mlab817** [claide/covid19pinas#1]
In the [cases](https://covidph.live/cases) page, when you filter the cases, the pagination does not update. You might want to fix that as it makes it difficult to navigate through the pages. (You don't know where it ends).

You may also want to add an indicator of how many matches were found as well as footnote on what `-` means.

Sorting through the table would also be helpful or some other options to filter the records (e.g. show only Quezon City, show only male, etc.).

Other than that, really good work!

**Comment by claide** [comment]
@mlab817 Ahaaa!, thanks for posting the issue here and for adding some good advice. I will update the app when I got time. Thanks again

**Comment by claide** [comment]
Fixed in [v2.0.1](https://github.com/claide/covid19pinas/releases/tag/v2.0.1)
